### ISSUE TITLE
Fala que estado está com problemas??

### ISSUE THREAD

**Issue by Dansk00** [lucassdoliveira/cielo3.0#12]
Estou utilizando magento 1.9 puro, sem nenhum módulo nem se quer a tradução, TEMA RWD, coloquei apenas o módulo cielo, e ao tentar realizar um teste fica apresentando erro abaixo:

Verifique o cadastro de Estado

Engraçado que algumas vezes nao apresentou e funcionou, mas depois nunca mais!!

log:

2018-03-07T19:45:30+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Verifique o cadastro de Estado' in /home/tecnolo2/public_html/magento/app/Mage.php:595
Stack trace:
#0 /home/tecnolo2/public_html/magento/app/code/community/Nitroecom/Cielo/Model/Payment.php(245): Mage::throwException('Verifique o cad...')
#1 /home/tecnolo2/public_html/magento/app/code/community/Nitroecom/Cielo/Model/Payment.php(441): Nitroecom_Cielo_Model_Payment->authorize(Object(Mage_Sales_Model_Order_Payment), '6')
#2 /home/tecnolo2/public_html/magento/app/code/core/Mage/Sales/Model/Order/Payment.php(443): Nitroecom_Cielo_Model_Payment->capture(Object(Mage_Sales_Model_Order_Payment), '6')
#3 /home/tecnolo2/public_html/magento/app/code/core/Mage/Sales/Model/Order/Invoice.php(395): Mage_Sales_Model_Order_Payment->capture(Object(Mage_Sales_Model_Order_Invoice))
#4 /home/tecnolo2/public_html/magento/app/code/core/Mage/Sales/Model/Order/Payment.php(608): Mage_Sales_Model_Order_Invoice->capture()
#5 /home/tecnolo2/public_html/magento/app/code/core/Mage/Sales/Model/Order/Payment.php(410): Mage_Sales_Model_Order_Payment->_invoice()
#6 /home/tecnolo2/public_html/magento/app/code/core/Mage/Sales/Model/Order/Payment.php(348): Mage_Sales_Model_Order_Payment->capture(NULL)
#7 /home/tecnolo2/public_html/magento/app/code/core/Mage/Sales/Model/Order.php(896): Mage_Sales_Model_Order_Payment->place()
#8 /home/tecnolo2/public_html/magento/app/code/core/Mage/Sales/Model/Order.php(1114): Mage_Sales_Model_Order->_placePayment()
#9 [internal function]: Mage_Sales_Model_Order->place()
#10 /home/tecnolo2/public_html/magento/app/code/core/Mage/Core/Model/Resource/Transaction.php(105): call_user_func(Array)
#11 /home/tecnolo2/public_html/magento/app/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction->_runCallbacks()
#12 /home/tecnolo2/public_html/magento/app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save()
#13 /home/tecnolo2/public_html/magento/app/code/core/Mage/Sales/Model/Service/Quote.php(249): Mage_Sales_Model_Service_Quote->submitOrder()
#14 /home/tecnolo2/public_html/magento/app/code/core/Mage/Checkout/Model/Type/Onepage.php(815): Mage_Sales_Model_Service_Quote->submitAll()
#15 /home/tecnolo2/public_html/magento/app/code/core/Mage/Checkout/controllers/OnepageController.php(599): Mage_Checkout_Model_Type_Onepage->saveOrder()
#16 /home/tecnolo2/public_html/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_OnepageController->saveOrderAction()
#17 /home/tecnolo2/public_html/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#18 /home/tecnolo2/public_html/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#19 /home/tecnolo2/public_html/magento/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#20 /home/tecnolo2/public_html/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#21 /home/tecnolo2/public_html/magento/index.php(83): Mage::run('', 'store')
#22 {main}

Alguém tem uma luz??

Quero agradecer ao Lucas pela criação do módulo!!

**Comment by barretinh0** [comment]
Olá,

Veja no "shipping address" (primeiro passo do registro no checkout), se não tem um input com display none. Comigo tinha um, dei um display block, adicionei um estado qualquer e foi.

**Comment by Dansk00** [comment]
Vou verificar agora e te falo!!

**Comment by Dansk00** [comment]
Infelizmente nao deu certo!  continua apresentando o mesmo erro, eu alterei dois arquivos sao eles:

/app/design/frontend/rwd/default/template/checkout/onepage/shipping.phtml

Antes: 

` <div class="field">
                            <label for="shipping:region" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                            <div class="input-box">
                                <select id="shipping:region_id" name="shipping[region_id]" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display:none;">
                                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                </select>
                                <script type="text/javascript">
                                //<![CDATA[
                                    $('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                                //]]>
                                </script>
                                <input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="**display:none**;" />
                            </div>`

depois:

` <div class="field">
                            <label for="shipping:region" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                            <div class="input-box">
                                <select id="shipping:region_id" name="shipping[region_id]" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display:block;">
                                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                </select>
                                <script type="text/javascript">
                                //<![CDATA[
                                    $('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                                //]]>
                                </script>
                                <input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:block;" />
                            </div>
                        </div>`



e também alterei este outro:

public_html/magento/app/design/frontend/rwd/default/template/persistent/checkout/onepage/billing.phtml

antes:

`<div class="field">
                        <label for="billing:region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                        <div class="input-box">
                            <select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display:none;">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                            //<![CDATA[
                                $('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                            //]]>
                            </script>
                            <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->quoteEscape($this->__('State/Province')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                        </div>
                    </div>`


Depois:

`<div class="field">
                        <label for="billing:region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                        <div class="input-box">
                            <select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display:block;">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                            //<![CDATA[
                                $('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                            //]]>
                            </script>
                            <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->quoteEscape($this->__('State/Province')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:block;" />
                        </div>
                    </div>`







Note que eu alterei de cada arquivo duas ações de display:none; para display:block;

Será que alterei errado? pois nao surtiu efeito. 

Agradeço o retorno amigo!!

**Comment by lucassdoliveira** [comment]
Olá amigo, baixa a tradução do Mario Sam e importa para seu e-commerce, esse erro esta acontecendo pois você não tem cadastrado os estados brasileiros.

 

 

Grande Abraço.

 

Qualquer dúvida entre em contato.

Atenciosamente

 

Lucas Soares de Oliveira

Analista e-commerce



 <http://www.nitroecom.com.br/> http://www.nitroecom.com.br 

Fone: (48) 3081-0076

Whatsapp Suporte: (48) 9.9101-1318

Skype:  <mailto:suporte@nitroecom.com.br> suporte@nitroecom.com.br

 

De: Dansk00 <notifications@github.com> 
Enviada em: quarta-feira, 7 de março de 2018 22:36
Para: lucassdoliveira/cielo3.0 <cielo3.0@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [lucassdoliveira/cielo3.0] Fala que estado está com problemas?? (#12)

 

Infelizmente nao deu certo! continua apresentando o mesmo erro, eu alterei dois arquivos sao eles:

/app/design/frontend/rwd/default/template/checkout/onepage/shipping.phtml

Antes:

<div class="field"> <label for="shipping:region" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label> <div class="input-box"> <select id="shipping:region_id" name="shipping[region_id]" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display:none;"> <option value=""><?php echo $this->__('Please select region, state or province') ?></option> </select> <script type="text/javascript"> //<![CDATA[ $('shipping:region_id').setAttribute('defaultValue', "<?php echo $this->getAddress()->getRegionId() ?>"); //]]> </script> <input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="**display:none**;" /> </div>

depois:

<div class="field"> <label for="shipping:region" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label> <div class="input-box"> <select id="shipping:region_id" name="shipping[region_id]" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display:block;"> <option value=""><?php echo $this->__('Please select region, state or province') ?></option> </select> <script type="text/javascript"> //<![CDATA[ $('shipping:region_id').setAttribute('defaultValue', "<?php echo $this->getAddress()->getRegionId() ?>"); //]]> </script> <input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:block;" /> </div> </div>

e também alterei este outro:

public_html/magento/app/design/frontend/rwd/default/template/persistent/checkout/onepage/billing.phtml

antes:

<div class="field"> <label for="billing:region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label> <div class="input-box"> <select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display:none;"> <option value=""><?php echo $this->__('Please select region, state or province') ?></option> </select> <script type="text/javascript"> //<![CDATA[ $('billing:region_id').setAttribute('defaultValue', "<?php echo $this->getAddress()->getRegionId() ?>"); //]]> </script> <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" title="<?php echo $this->quoteEscape($this->__('State/Province')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" /> </div> </div>

Depois:

<div class="field"> <label for="billing:region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label> <div class="input-box"> <select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display:block;"> <option value=""><?php echo $this->__('Please select region, state or province') ?></option> </select> <script type="text/javascript"> //<![CDATA[ $('billing:region_id').setAttribute('defaultValue', "<?php echo $this->getAddress()->getRegionId() ?>"); //]]> </script> <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" title="<?php echo $this->quoteEscape($this->__('State/Province')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:block;" /> </div> </div>

Note que eu alterei de cada arquivo duas ações de display:none; para display:block;

Será que alterei errado? pois nao surtiu efeito.

Agradeço o retorno amigo!!

**Comment by lucassdoliveira** [comment]
Provavelmente essa e uma obrigatoriedade da API da cielo, conter dois caracteres para reapresentar estado.

Da uma olhadinha na documentação, na descrição do modulo tem o link para essa documentação.

**Comment by Dansk00** [comment]
Blzzz!! Lucas muito obrigado! e parabéns pelo esforço para com a comunidade!! agora já tenho um rumo de trabalho em cima desse módulo qualquer coisa eu volto aqui e posto novidades!! vou ler a documentação e dar umas alteradas la!

abraços!!

**Comment by LucsDantas** [comment]
Conseguiu arrumar o problema? estou com o mesmo e tentei de tudo e não consegui arrumar
